stages:
  build:
    nodeLabel: sbt
    steps:
      - sbt test universal:packageBin
    filesToStash:
      - '**'
  publish:
    nodeLabel: nvm-sbt-deployer
    steps:
      - |
        export ACCOUNT=455620323323
        export STAGE=Admin
        export BUCKET=dwolla-code
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm && npm install -g serverless
        sbt deploy
