service: iam-user-cleanup

provider:
  name: aws
  runtime: java11
  memorySize: 1024
  timeout: 60
  region: us-west-2
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:BUCKET}
    serverSideEncryption: "AES256"
  iam:
    deploymentRole: "arn:aws:iam::${env:ACCOUNT}:role/cloudformation/deployer/cloudformation-deployer"
    role:
      statements:
        - Effect: Allow
          Action:
           - iam:ListAccessKeys
           - iam:ListVirtualMFADevices
           - iam:ListMFADevices
           - iam:DeleteAccessKey
           - iam:DeleteVirtualMFADevice
           - iam:DeactivateMFADevice
          Resource: '*'
  logRetentionInDays: 7
  stackTags:
    Creator: serverless
    Environment: ${env:STAGE}
    Project: ${self:service}
    Team: platform
    Visibility: internal
  lambdaHashingVersion: 20201221

package:
  artifact: ${env:ARTIFACT_PATH}

functions:
  IamUserCleanup:
    handler: com.dwolla.lambda.iam.Handler

resources:
  Description: CloudFormation custom resource to remove IAM User keys/MFA tokens that would otherwise prevent an IAM user from being removed by CloudFormation
  Outputs:
    Function:
      Description: Lambda Function Service Token
      Value:
        'Fn::GetAtt': [IamUserCleanupLambdaFunction, Arn]
      Export:
        Name: ${self:service}:${env:STAGE}:IamUserCleanupArn
