service: iam-user-cleanup
useDotenv: true
frameworkVersion: ^3.2.1

provider:
  name: aws
  runtime: java11
  memorySize: 1024
  timeout: 60
  region: us-west-2
  deploymentBucket:
    name: ${env:BUCKET}
    serverSideEncryption: "AES256"
  iam:
    deploymentRole: "arn:aws:iam::${env:ACCOUNT}:role/cloudformation/deployer/cloudformation-deployer"
    role:
      statements:
        - Effect: Allow
          Action:
           - iam:ListAccessKeys
           - iam:ListVirtualMFADevices
           - iam:ListMFADevices
           - iam:DeleteAccessKey
           - iam:DeleteVirtualMFADevice
           - iam:DeactivateMFADevice
           - iam:ListSSHPublicKeys
           - iam:DeleteSSHPublicKey
          Resource: '*'
  logRetentionInDays: 7
  stackTags:
    Creator: serverless
    Environment: ${opt:stage}
    Project: ${self:service}
    Team: platform
    Visibility: internal

package:
  artifact: ${env:ARTIFACT_PATH}

functions:
  IamUserCleanup:
    handler: com.dwolla.lambda.iam.Handler

resources:
  Description: CloudFormation custom resource to remove IAM User keys/MFA tokens that would otherwise prevent an IAM user from being removed by CloudFormation
  Outputs:
    Function:
      Description: Lambda Function Service Token
      Value:
        'Fn::GetAtt': [IamUserCleanupLambdaFunction, Arn]
      Export:
        Name: ${self:service}:${opt:stage}:IamUserCleanupArn
